kubeconfig_location: "/root/.kube"
kustomize_version: "5.4.2"
kubectl_version: "1.24.6"
argocd_cli_version: "2.11.3"
cluster_name: envname
kubeconfig_local_location: "/tmp"
helmfile_version: "0.165.0"
#argo
argocd_override:
argocd_default:
  argocd_appname: argocd
  gitrepo_owner: mojaloop
  gitrepo_repo: iac-modules
  initial_argo_gitrepo_path: gitops/base/argo-apps
  root_app_gitrepo_path: gitops/overlays/local/argo-apps
  gitrepo_host_fqdn: "https://github.com/"
  gitrepo_raw_host_fqdn: "https://raw.githubusercontent.com"
  initial_application_gitrepo_tag: "vexp-cck8s19"
  apps:
    argocd:
      # needs to match sub_apps.argocd_helm.app_name, due to chart issue.
      argocd_app_name: "argocd"
      app_namespace: "argocd"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "-11"
      app_enabled: true
      sub_apps:
        argocd_helm:
          app_name: "argocd"
          namespace: "argocd"
          helm_version: "7.1.5"
          public_ingress_access_domain: false
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
          sub_app_enabled: true
    utils:
      argocd_app_name: "utils"
      namespace: "utils"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "-10"
      app_enabled: true
      sub_apps:
        rook_ceph:
          app_name: "rook-ceph"
          namespace: "rook-ceph"
          helm_version: "1.14.5"
          rook_csi_kubelet_dir_path: "/var/snap/microk8s/common/var/lib/kubelet"
          sub_app_enabled: true
        reflector:
          app_name: "reflector"
          helm_version: "7.1.262"
          namespace: "default"
          sub_app_enabled: true
        crossplane:
          app_name: "crossplane"
          helm_version: "1.16.0"
          namespace: "crossplane-system"
          debug: "debug"
          sub_app_enabled: true
        kubernetes_secret_generator:
          app_name: "kubernetes-secret-generator"
          helm_version: "3.4.0"
          namespace: "default"
          sub_app_enabled: true
        external_secrets:
          app_name: "external-secrets"
          helm_version: "0.9.0"
          namespace: "external-secrets"
          sub_app_enabled: true
        cert_manager:
          app_name: "cert-manager"
          helm_version: "1.15.0"
          namespace: "cert-manager"
          letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"
          letsencrypt_email: "none@example.com"
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
          sub_app_enabled: true
        ext_dns:
          app_name: "ext-dns"
          helm_version: "7.5.5"
          namespace: "ext-dns"
          dns_cloud_api_client_secret: "none"
          dns_cloud_api_client_id: "none"
          dns_cloud_api_region: "none"
          sub_app_enabled: true
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
    vault:
      argocd_app_name: "vault"
      app_enabled: true
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "-9"
      sub_apps:
        vault:
          app_name: "vault"
          sub_app_enabled: true
          namespace: "vault"
          helm_version: "0.24.1"
          public_ingress_access_domain: false
          vault_keys_secret: "vault-keys"
          vault_tf_provider_version: "~> 3.16"
          vault_terraform_modules_tag: "vexp-cck8s19"
          vault_log_level: "info"
          vault_rbac_admin_group: "techops-admin"
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
        consul:
          app_name: "consul"
          sub_app_enabled: true
          namespace: "consul"
          helm_version: "1.4.0"
          public_ingress_access_domain: false
          replicas: 1
          storage_size: 3Gi
    istio:
      argocd_app_name: "istio"
      app_enabled: true
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "-7"
      sub_apps:
        istio:
          app_name: istio
          sub_app_enabled: true
          proxy_log_level: "info"
          namespace: "istio-system"
          helm_version: "1.22.1"
          external_ingress_https_port: 32443
          external_ingress_http_port: 32080
          external_ingress_health_port: 32081
          internal_ingress_https_port: 31443
          internal_ingress_http_port: 31080
          internal_ingress_health_port: 31081
          istio_internal_gateway_name: "istio-internal-ingress-gw"
          istio_external_gateway_name: "istio-external-ingress-gw"
          istio_internal_wildcard_gateway_name: "internal-wildcard-gateway"
          istio_external_wildcard_gateway_name: "external-wildcard-gateway"
          istio_external_gateway_namespace: "istio-ingress-ext"
          istio_internal_gateway_namespace: "istio-ingress-int"
          internal_load_balancer_dns: "dns.name"
          external_load_balancer_dns: "dns.name"
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
    zitadel:
      argocd_app_name: "zitadel"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "-6"
      app_enabled: true
      sub_apps:
        zitadel:
          app_name: "zitadel"
          sub_app_enabled: true
          namespace: "zitadel"
          cockroachdb_helm_version: "11.2.1"
          helm_version: "7.15.0"
          tf_provider_version: "~> 1.2"
          terraform_modules_tag: "vexp-cck8s19"
          vault_rbac_admin_group: "techops-admin"
          zitadel_grant_prefix: "zitadel:grants"
          public_ingress_access_domain: true
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
        cockroach_db:
          app_name: "cockroach-db"
          sub_app_enabled: true
          namespace: "zitadel"
          helm_version: "11.2.1"
    netbird:
      argocd_app_name: "netbird"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "-5"
      app_enabled: true
      sub_apps:
        netbird:
          app_name: "netbird"
          sub_app_enabled: true
          helm_version: "1.0.2"
          dashboard_chart_version: "1.0.0"
          image_version: "0.28.0"
          namespace: "netbird"
          preconfig_secret: "netbird-management"
          management_turn_secret: "netbird-turn"
          stunner_system_namespace: "stunner-system"
          stunner_nodeport_port: 31821
          stunner_impl_namespace: stunner-impl
          stunner_auth_secret: stunner-auth-secret
          terraform_modules_tag: "vexp-cck8s19"
          public_ingress_access_domain: true
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
