teardown: false
kubeconfig_location: "/root/.kube"
kustomize_version: "5.4.2"
kubectl_version: "1.24.6"
argocd_cli_version: "2.11.3"
cluster_name: envname
kubeconfig_local_location: "/tmp"
helmfile_version: "0.165.0"
helm_version: "3.14.0"
cluster_cloud_provider: "aws"
#argo
argocd_override:
argocd_default:
  argocd_appname: argocd
  gitrepo_owner: mojaloop
  gitrepo_repo: iac-modules
  initial_argo_gitrepo_path: gitops/argo-apps/base
  root_app_gitrepo_path: gitops/argo-apps/overlays/local
  gitrepo_host_fqdn: "https://github.com/"
  gitrepo_raw_host_fqdn: "https://raw.githubusercontent.com"
  initial_application_gitrepo_tag: "vexp-cck8s19"
  namespace: "argocd"
  ansible_gitrepo: iac-ansible-collection-roles
  ansible_collection_path: mojaloop/iac
  apps:
    utils:
      argocd_app_name: "utils"
      app_namespace: "argocd"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "'-10'"
      app_enabled: "true"
      sub_apps:
        argocd_helm:
          app_name: "argocd"
          namespace: "argocd"
          helm_version: "7.3.2"
          public_ingress_access_domain: "false"
          sub_app_enabled: "true"
        rook_ceph:
          app_name: "rook-ceph"
          namespace: "rook-ceph"
          helm_version: "1.14.5"
          rook_csi_kubelet_dir_path: "/var/snap/microk8s/common/var/lib/kubelet"
          sub_app_enabled: "true"
        reflector:
          app_name: "reflector"
          helm_version: "7.1.262"
          namespace: "default"
          sub_app_enabled: "true"
        reloader:
          app_name: "reloader"
          helm_version: "1.0.67"
          namespace: "default"
          sub_app_enabled: "true"
        crossplane:
          app_name: "crossplane"
          helm_version: "1.16.0"
          namespace: "crossplane-system"
          debug: "debug"
          sub_app_enabled: "true"
        percona:
          app_name: "percona-postgresql-operator"
          helm_version: "2.4.0"
          namespace: "percona"
          debug: "debug"
          sub_app_enabled: "true"
        redis:
          app_name: "redis-operator"
          helm_version: "0.16.4"
          namespace: "redis"
          debug: "debug"
        kubernetes_secret_generator:
          app_name: "kubernetes-secret-generator"
          helm_version: "3.4.0"
          namespace: "default"
          sub_app_enabled: "true"
        external_secrets:
          app_name: "external-secrets"
          helm_version: "0.9.20"
          namespace: "external-secrets"
          sub_app_enabled: "true"
        istio:
          app_name: istio
          sub_app_enabled: "true"
          proxy_log_level: "debug"
          namespace: "istio-system"
          helm_version: "1.22.1"
          external_ingress_https_port: "'32443'"
          external_ingress_http_port: "'32080'"
          external_ingress_health_port: "'32081'"
          internal_ingress_https_port: "'31443'"
          internal_ingress_http_port: "'31080'"
          internal_ingress_health_port: "'31081'"
          external_gateway_namespace: "istio-ingress-ext"
          internal_gateway_namespace: "istio-ingress-int"
          internal_gateway_name: "istio-internal-ingress-gw"
          external_gateway_name: "istio-external-ingress-gw"
          gw_sync_wave: "'-9'" # hack to start gw after istiod
        cert_manager:
          app_name: "cert-manager"
          helm_version: "1.15.0"
          namespace: "cert-manager"
          sub_app_enabled: "true"
          credentials_secret: "cert-manager-dns"
        consul:
          app_name: "consul"
          sub_app_enabled: "true"
          namespace: "consul"
          helm_version: "1.4.0"
          replicas: "'1'"
          storage_size: 3Gi
          sync_wave: "'-9'"
        post_config:
          app_name: "post-config"
          sync_wave: "'-9'"
          vault_crossplane_modules_version: "1.0.0"
          terraform_crossplane_modules_version: "0.16.0"
          ansible_crossplane_modules_version: "0.6.0"
    vault:
      argocd_app_name: "vault"
      app_namespace: "argocd"
      app_enabled: "true"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "'-8'"
      sub_apps:
        vault:
          app_name: "vault"
          sub_app_enabled: "true"
          namespace: "vault"
          helm_version: "0.24.1"
          public_ingress_access_domain: "false"
          vault_keys_secret: "vault-keys"
          vault_tf_provider_version: "~> 3.16"
          vault_terraform_modules_tag: "vexp-cck8s19"
          vault_log_level: "trace"
          cloud_platform_api_client_id: "id"
          cloud_platform_api_client_secret: "secret"
          vault_kv_secret: "secret"
          vault_tf_post_config_output_secret: "vault-tf-post-config"
        vault_config_operator:
          app_name: "vault-config-operator"
          sub_app_enabled: "true"
          namespace: "vault-config"
          helm_version: "0.8.28"
        post_config:
          app_name: "post-config"
          sync_wave: "'-7'"
          vault_read_all_kv_secrets_policy_name: "read-all-kv"
          vault_k8s_admin_auth_path: "admin-k8s"
          vault_k8s_admin_role_name: "admin-role"

    dns_utils:
      argocd_app_name: "dns-utils"
      app_namespace: "argocd"
      app_enabled: "true"
      application_gitrepo_tag: "vexp-cck8s19"
      sync_wave: "'-5'"
      sub_apps:
        ext_dns:
          app_name: "ext-dns"
          helm_version: "7.5.5"
          namespace: "ext-dns"
          sub_app_enabled: "true"
        cr_config:
          app_name: "cr-config"
          sub_app_enabled: "true"
          istio_internal_gateway_name: "istio-internal-ingress-gw"
          istio_external_gateway_name: "istio-external-ingress-gw"
          istio_internal_wildcard_gateway_name: "internal-wildcard-gateway"
          istio_external_wildcard_gateway_name: "external-wildcard-gateway"
          istio_external_gateway_namespace: "istio-ingress-ext"
          istio_internal_gateway_namespace: "istio-ingress-int"
          internal_load_balancer_dns: "dns.name"
          external_load_balancer_dns: "dns.name"
          dns_public_subdomain: "x.y.z"
          dns_private_subdomain: "x.y.internal"
          ext_dns_cloud_policy: "arn:blah"
          dns_cloud_api_region: "none"
          letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"
          letsencrypt_email: "none@example.com"
          cert_manager_namespace: "cert-manager"
        post_config:
          app_name: "post-config"
          sub_app_enabled: "true"
          sync_wave: "'-4'"
        pre:
          app_name: "pre"
          sub_app_enabled: "true"
          sync_wave: "'-6'"
    security:
      argocd_app_name: "security"
      application_gitrepo_tag: "vexp-cck8s19"
      app_namespace: "argocd"
      sync_wave: "'-3'"
      app_enabled: "true"
      sub_apps:
        zitadel:
          app_name: "zitadel"
          sub_app_enabled: "true"
          sync_wave: "'-2'"
          namespace: "zitadel"
          helm_version: "7.15.0"
          zitadel_tf_provider_version: "~> 1.2"
          terraform_modules_tag: "vexp-cck8s19"
          vault_rbac_admin_group: "techops-admin"
          zitadel_grant_prefix: "zitadel:grants"
          public_ingress_access_domain: "true"
          zitadel_post_config_output_secret: "post-config-output"
          argocd_oidc_secret: "argo-oidc-secret"
          argocd_user_rbac_group: "argocd_users"
          argocd_admin_rbac_group: "argocd_administrators"
          post_config_sync_wave: "'-1'"
        cockroachdb:
          app_name: "cockroach-db"
          sub_app_enabled: "true"
          helm_version: "13.0.2"
          pvc_size: "5Gi"
        netbird:
          app_name: "netbird"
          sub_app_enabled: "true"
          sync_wave: "'1'"
          helm_version: "1.0.2"
          image_version: "0.28.0"
          dashboard_helm_version: "1.0.0"
          dashboard_image_version: "v2.4.0"
          namespace: "netbird"
          preconfig_output_secret: "netbird-management"
          stunner_system_namespace: "stunner-system"
          stunner_gateway_operator_helm_version: "0.19.0"
          stunner_nodeport_port: "'31821'"
          stunner_impl_namespace: stunner-impl
          stunner_auth_secret: stunner-auth-secret
          terraform_modules_tag: "vexp-cck8s19"
          public_ingress_access_domain: "true"
          pre_sync_wave: "'0'"
    nexus:
      argocd_app_name: "nexus"
      app_namespace: "argocd"
      app_enabled: "true"
      application_gitrepo_tag: "cto-102-nexus-01"
      sync_wave: "'-3'"
      sub_apps:
        nexus:
          app_name: "nexus"
          helm_version: "4.44.0"
          namespace: "nexus"
          public_ingress_access_domain: "true"
        pre:
          app_name: "pre"
          sub_app_enabled: "true"
          sync_wave: "'-4'"
          vault_k8s_admin_auth_path: "admin-k8s"
          vault_k8s_admin_role_name: "admin-role"
        post_config:
          app_name: "nexus-post-config"
          sub_app_enabled: "true"
          sync_wave: "'-2'"
          ansible_collection_tag: "vexp-cck8s19"

    gitlab:
      argocd_app_name: "gitlab"
      app_namespace: "argocd"
      app_enabled: "true"
      application_gitrepo_tag: "vexp-cck8sargoroot95"
      sync_wave: "'-1'"
      sub_apps:
        gitlab:
          app_name: "gitlab"
          helm_version: "8.1.2"
          namespace: "gitlab"
          public_ingress_access_domain: "true"
        pre:
          app_name: "pre"
          sub_app_enabled: "true"
          sync_wave: "'-1'"
          redis_cluster_size: "'3'"
          postgres_replicas: "'1'"
          postgres_proxy_replicas: "'1'"
          postgres_storage_size: "10Gi"
          pgdb_helm_version: "2.4.0"
        post_config:
          app_name: "gitlab-post-config"
          sub_app_enabled: "true"
          sync_wave: "'-2'"
          ansible_collection_tag: "vexp-cck8s19"
