argocd_version: "2.8.2"
rook_ceph_version: "1.14.5"
rook_ceph_namespace: "rook-ceph"
external_secrets_version: "0.9.0"
external_secrets_namespace: "external-secrets"
kubeconfig_location: "/root/.kube"
cluster_name: envname
kubeconfig_local_location: "/tmp"
kustomize_version: "3.2.3"
kubectl_version: "1.24.6"
rook_csi_kubelet_dir_path: "/var/snap/microk8s/common/var/lib/kubelet"
rook_gitrepo_location: "/tmp/rook"
