argocd_version: "2.8.2"
rook_ceph_version: "1.14.5"
rook_ceph_namespace: "rook-ceph"
external_secrets_version: "0.9.0"
external_secrets_namespace: "external-secrets"
kubeconfig_location: "/root/.kube"
cluster_name: envname
kubeconfig_local_location: "/tmp"
zitadel_local_location: "/tmp"
kustomize_version: "5.4.2"
kubectl_version: "1.24.6"
rook_csi_kubelet_dir_path: "/var/snap/microk8s/common/var/lib/kubelet"
rook_gitrepo_location: "/tmp/rook"
zitadel_namespace: "zitadel"
cockroachdb_helm_version: "11.2.1"
zitadel_helm_version: "7.15.0"
rook_ceph_storage_class: "rook-ceph-block"
netbird_chart_version: "1.0.2"
netbird_dashboard_chart_version: "1.0.0"
netbird_image_version: "0.28.0"
netbird_namespace: "netbird"
netbird_preconfig_secret: "netbird-management"
netbird_management_turn_secret: "netbird-turn"
certmanager_helm_version: "1.15.0"
certmanager_namespace: "cert-manager"
external_dns_helm_version: "7.5.5"
external_dns_namespace: "ext-dns"
external_dns_credentials_secret: "ext-dns-secret"
letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"
letsencrypt_email: "none@example.com"
dns_cloud_api_client_secret: "none"
dns_cloud_api_client_id: "none"
dns_cloud_api_region: "none"
dns_public_subdomain: "x.y.z"
dns_private_subdomain: "x.y.internal"
istio_proxy_log_level: "info"
istio_namespace: "istio-system"
istio_helm_version: "1.22.1"
istio_internal_gateway_name: "istio-internal-ingress-gw"
istio_external_gateway_name: "istio-external-ingress-gw"
istio_internal_wildcard_gateway_name: "internal-wildcard-gateway"
istio_external_wildcard_gateway_name: "external-wildcard-gateway"
istio_external_gateway_namespace: "istio-ingress-ext"
istio_internal_gateway_namespace: "istio-ingress-int"
default_external_ssl_certificate: "ext-ingress-letsencrypt"
default_internal_ssl_certificate: "int-ingress-letsencrypt"
external_ingress_https_port: 32443
external_ingress_http_port: 32080
external_ingress_health_port: 32081
internal_ingress_https_port: 31443
internal_ingress_http_port: 31080
internal_ingress_health_port: 31081
internal_load_balancer_dns: "dns.name"
external_load_balancer_dns: "dns.name"
reflector_helm_version: "7.1.262"
crossplane_helm_version: "1.16.0"
crossplane_namespace: "crossplane-system"
zitadel_tf_provider_version: "~> 1.2"
zitadel_terraform_modules_tag: "vexp-cck8s19"
helmfile_version: "0.165.0"
stunner_system_namespace: "stunner-system"
stunner_nodeport_port: 31821
stunner_impl_namespace: stunner-impl
stunner_auth_secret: stunner-auth-secret
consul_replicas: 1
consult_storage_size: 3Gi
consul_namespace: consul
vault_namespace: vault
consul_helm_version: "1.4.0"
vault_helm_version: "0.24.1"
vault_keys_secret: "vault-keys"
vault_tf_provider_version: "~> 3.16"
vault_terraform_modules_tag: "vexp-cck8s19"
netbird_terraform_modules_tag: "vexp-cck8s19"
vault_rbac_admin_group: "techops-admin"
zitadel_grant_prefix: "zitadel:grants"
vault_log_level: "info"
crossplane_debug: "debug"
kubernetes_secret_generator_helm_version: "3.4.0"

#argo
argo_release_name: "argocd"
argo_release_version: "7.1.5"
argocd_cli_version: "2.11.3"
argocd_application_gitrepo_tag: "vexp-cck8s19"
argocd_gitrepo_owner: mojaloop
argocd_gitrepo_repo: iac-modules
argocd_gitrepo_path: gitops/argocd
