#Create a temporary directory for storing values files or other config
- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0700

- name: install kustomize
  get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v{{ kustomize_version }}/kustomize_kustomize.v{{ kustomize_version }}_linux_amd64
    dest: /usr/local/bin/kustomize
    mode: 0700

- name: Create temporary directory for cc boot
  tempfile:
    state: directory
    suffix: values
  register: cctmpvalues

- name: "create directory for kubeconfig"
  file:
    path: "{{ kubeconfig_location }}"
    state: directory
    recurse: yes

- name: "create directory for rook git repo"
  file:
    path: "{{ rook_gitrepo_location }}"
    state: directory
    recurse: yes

- name: copy kubeconfig
  copy:
    src: "{{ kubeconfig_local_location }}/kubeconfig"
    dest: "{{ kubeconfig_location }}/kubeconfig"
    mode: "0600"

- name: apply node labels
  shell: |
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig label --overwrite nodes {{ item.node_name }} {% for labels in lookup('dict', item.node_labels, wantlist=True) %} {{ labels.key }}={{ labels.value }}{% endfor %}
  loop: "{{ node_pool_labels }}"
  when: node_pool_labels is defined

- name: apply node taints
  shell: |
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig taint --overwrite nodes {{ item.node_name }} {% for taints in lookup('dict', item.node_taints, wantlist=True) %} {{ taints.value }}{% endfor %}
  loop: "{{ node_pool_taints }}"
  when: node_pool_taints is defined

- name: Upload cc bootstrap files
  template:
    src: "templates/{{ item }}.yaml.j2"
    dest: "{{ cctmpvalues.path }}/{{ item }}.yaml"
  with_items:
    - kustomization
    - rook-ceph-crs
    - cockroach-db-values
    - zitadel-cert-job
    - zitadel-values
    - netbird-values
    - lets-encrypt-cluster-issuer
    - ext-dns-values
    - ext-dns-crs
    - istio-istiod-values
    - istio-base-values

- name: Install rook/ceph
  shell: |
    cd {{ rook_gitrepo_location }}
    git config --global advice.detachedHead false
    rm -rf rook
    git clone https://github.com/rook/rook.git
    cd rook
    git checkout v{{ rook_ceph_version }}
    cp deploy/examples/crds.yaml deploy/examples/common.yaml deploy/examples/operator.yaml  {{ cctmpvalues.path }}
    kustomize build {{ cctmpvalues.path }} > {{ cctmpvalues.path }}/rook-deploy.yaml
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl apply -f {{ cctmpvalues.path }}/rook-deploy.yaml
    kubectl apply -f {{ cctmpvalues.path }}/rook-ceph-crs.yaml
    kubectl -n rook-ceph wait --for=jsonpath='{.status.phase}'=Ready CephBlockPool/replicapool
    #change sc to default
    export default_sc=$(kubectl get sc -o jsonpath='{.items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")].metadata.name}')    
    if [ "{{ rook_ceph_storage_class }}" != "$default_sc" ]; then kubectl patch storageclass $default_sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'; fi
    kubectl patch storageclass {{ rook_ceph_storage_class }} -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

- name: Install utils
  shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    helm repo add istio https://istio-release.storage.googleapis.com/charts
    helm upgrade --install istio-base istio/base --version {{ istio_helm_version }} -n {{ istio_namespace }} --create-namespace --values {{ cctmpvalues.path }}/istio-base-values.yaml
    helm upgrade --install istio-istiod istio/istiod --version {{ istio_helm_version }} -n {{ istio_namespace }} --create-namespace --values {{ cctmpvalues.path }}/istio-istiod-values.yaml
    helm repo add cert-manager https://charts.jetstack.io
    helm upgrade --install cert-manager cert-manager/cert-manager --version {{ certmanager_helm_version }} -n {{ certmanager_namespace }} --create-namespace --set crds.enabled=true
    kubectl -n {{ certmanager_namespace }} apply -f {{ cctmpvalues.path }}/lets-encrypt-cluster-issuer.yaml
    helm repo add bitnami https://charts.bitnami.com/bitnami
    helm upgrade --install external-dns bitnami/external-dns --version {{ external_dns_helm_version }} -n {{ external_dns_namespace }} --create-namespace --values {{ cctmpvalues.path }}/ext-dns-values.yaml
    kubectl -n {{ external_dns_namespace }} create secret generic {{ external_dns_credentials_secret }} --from-file=credentials={{ cctmpvalues.path }}/ext-dns-crs.yaml

- name: Install zitadel
  shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    helm repo add cockroachdb https://charts.cockroachdb.com/
    helm upgrade --install zitadel-db cockroachdb/cockroachdb --version {{ cockroachdb_helm_version }} -n {{ zitadel_namespace }} --create-namespace --values {{ cctmpvalues.path }}/cockroach-db-values.yaml

    # Generate a TLS certificate for the zitadel DB user
    kubectl -n {{ zitadel_namespace }} apply -f {{ cctmpvalues.path }}/zitadel-cert-job.yaml
    kubectl -n {{ zitadel_namespace }} wait --for=condition=complete job/create-zitadel-cert

    # Install ZITADEL
    helm repo add zitadel https://charts.zitadel.com
    helm upgrade --install zitadel zitadel/zitadel --version {{ zitadel_helm_version }} -n {{ zitadel_namespace }} --values {{ cctmpvalues.path }}/zitadel-values.yaml

# - name: Install netbird
#   shell: |

#     # install netbird
#     helm repo add jaconi https://charts.jaconi.io
#     helm install netbird jaconi/netbird --version {{ netbird_chart_version }} --values {{ cctmpvalues.path }}/netbird-values.yaml
