- name: set facts
  import_tasks: setup_facts.yaml
  
- name: setup
  import_tasks: setup.yaml
  when: (not (teardown | bool))

- name: install
  import_tasks: install.yaml
  when: (not (teardown | bool))

- name: remove microk8s
  import_tasks: teardown.yaml
  when: (teardown | bool)
