- name: Delete argo apps
  shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl delete -f {{ cctmpvalues.path }}/argocd/root-app.yaml --wait=false
  args:
    executable: /bin/bash

- name: Wait for vault to be gone
  shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl patch workspace zitadel-post-config --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    kubectl patch workspace zitadel-argocd-oidc-config --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    kubectl patch workspace zitadel-vault-oidc-config --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    kubectl patch workspace vault-post-config --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig get application -n {{ fact_argo_merged_config.namespace }} vault
  register: outputapp
  until: outputapp is failed
  retries: 100
  delay: 30
  ignore_errors: true
