- name: Wait netmaker api server to respond
  uri:
    url: https://{{ netmaker_api_host }}/api/networks
    method: GET
    headers:
      Authorization: Bearer {{ netmaker_master_key }}
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 10 # Every 10 seconds
##get networks from netclient command line netclient list, loop over networks with nodeid
- name: Add egress gw
  uri:
    url: https://{{ netmaker_api_host }}/api/nodes/{{ item.0 }}/{{ item.1 }}/creategateway
    method: POST
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ netmaker_master_key }}
    body: "{{ lookup('template', 'creategw.json.j2') }}"
    body_format: json
    status_code: [200, 400]
  loop: "{{ netmaker_networks }}"
  loop_control:
    index_var: ipindex
