- name: Get netclient list output
  shell: "netclient list"
  register: _bastion_netclient

- name: delete bastion node
  uri:
    url: https://{{ netmaker_api_host }}/api/nodes/{{ item.network }}/{{ item.node_id }}
    method: DELETE
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ netmaker_master_key }}
    status_code: [200, 400]
  loop: "{{ _bastion_netclient.stdout }}"

- name: get nodes in env network
  uri:
    url: https://{{ netmaker_api_host }}/api/nodes/{{ netmaker_env_network_name }}
    method: GET
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ netmaker_master_key }}
    status_code: [200, 400]
  register: _env_nodes

- name: delete nodes in network
  uri:
    url: https://{{ netmaker_api_host }}/api/nodes/{{ item.network }}/{{ item.id }}
    method: DELETE
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ netmaker_master_key }}
    status_code: [200, 400]
  loop: "{{ _env_nodes.json }}"
