- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.bastion_common
    - mojaloop.iac.netclient

- hosts: master
  become: true
  roles:
    - mojaloop.iac.k3s_common
    - mojaloop.iac.argo_k3s_master

- hosts: agent
  become: true
  roles:
    - mojaloop.iac.k3s_common
    - mojaloop.iac.argo_k3s_worker

- hosts: master
  become: true
  roles:
    - geerlingguy.k8s.helm
    - mojaloop.iac.argocd