- hosts: agent
  become: true
  vars:
    teardown: true
  roles:
    - role: mojaloop.iac.microk8s

- hosts: master
  become: true
  vars:
    teardown: true
  roles:
    - role: mojaloop.iac.microk8s