- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.bastion_common
    - mojaloop.iac.docker

- hosts: "{{ groups['bastion'] | sort | first }}"
  become: true
  roles:
    - mojaloop.iac.eks_util
    - geerlingguy.k8s.helm
    #- mojaloop.iac.cc_k8s
    - mojaloop.iac.cc_eks