- hosts: netmaker
  become: true
  roles:
    - mojaloop.iac.docker
    - mojaloop.iac.netmaker

- hosts: bastion
  become: true
  roles:
    - role: mojaloop.iac.netclient
      vars:
        create_egress_gateway: true

- hosts: docker
  become: true
  roles:
    - mojaloop.iac.vault
