- name: Wait nexus to respond
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/status
    method: GET
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 10

- name: Get docker proxy repo if exists
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/repositories/docker/proxy/{{ item.name }}
    method: GET
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    status_code: [200, 404]
    timeout: 300
  register: docker_proxy_repos_exists
  with_items: "{{ docker_proxy_repos }}"


- name: Add docker proxy if not exists
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/repositories/docker/proxy
    method: POST
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    body: "{{ lookup('template', 'createdockerproxyrepo.json.j2') }}"
    body_format: json
    status_code: 201
    timeout: 300
  when: item.status == 404
  with_items: "{{ docker_proxy_repos_exists.results }}"

- name: Get helm proxy repo if exists
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/repositories/helm/proxy/{{ item.name }}
    method: GET
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    status_code: [200, 404]
    timeout: 300
  register: helm_proxy_repos_exists
  with_items: "{{ helm_proxy_repos }}"

- name: Add helm proxy if not exists
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/repositories/helm/proxy
    method: POST
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    body: "{{ lookup('template', 'createhelmproxyrepo.json.j2') }}"
    body_format: json
    status_code: 201
    timeout: 300    
  when: item.status == 404
  with_items: "{{ helm_proxy_repos_exists.results }}"

- name: Get docker group repo if exists
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/repositories/docker/group/{{ group_repo_name }}
    method: GET
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    status_code: [200, 404]
    timeout: 300    
  register: group_repo_exists

- name: Add docker group repo if not exists
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/repositories/docker/group
    method: POST
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    body: "{{ lookup('template', 'createdockergrouprepo.json.j2') }}"
    body_format: json
    status_code: 201
    timeout: 300    
  when: group_repo_exists.status == 404

- name: Set active realms
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/security/realms/active
    method: PUT
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    src: putrealmbody.json
    status_code: 204
    timeout: 300    

- name: Set anonymous access
  uri:
    url: http://{{ nexus_server }}/service/rest/v1/security/anonymous
    method: PUT
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    src: anonymousaccess.json
    status_code: 200
    timeout: 300    