- name: download awscli
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli_version }}.zip
    dest: /tmp
    remote_src: yes

- name: install aws
  shell: |
    /tmp/aws/install

- name: "create directory for aws profile"
  file:
    path: "/root/.aws"
    state: directory
    recurse: yes

- name: "copy credentials file"
  template:
    src: "../templates/credentials.j2"
    dest: "/root/.aws/credentials"

- name: "create directory for kubeconfig"
  file:
    path: "{{ kubeconfig_location }}"
    state: directory
    recurse: yes

- name: create kubeconfig
  shell: |
    aws eks update-kubeconfig --region {{ eks_aws_region }} --name {{ eks_cluster_name }} --kubeconfig {{ kubeconfig_location }}/kubeconfig

- name: Fetch kubeconfig
  fetch:
    src: "{{ kubeconfig_location }}/kubeconfig"
    dest: "{{ kubeconfig_local_location }}/kubeconfig"
    flat: yes
