vault_image_version: 1.13
vault_root_dir: /root/vault-compose
vault_listening_port: 8200
vault_fqdn: vault.domain.null
vault_region: eu-west-1
vault_acme_email: null@null.com
vault_gitlab_url: http://gitlab.url
vault_gitlab_token: "#crazytoken$"